// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"zero/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 购物车列表
				Method:  http.MethodGet,
				Path:    "/v1/cart/list",
				Handler: CartListHandler(serverCtx),
			},
			{
				// 分类商品列表
				Method:  http.MethodGet,
				Path:    "/v1/category/list",
				Handler: CategoryListHandler(serverCtx),
			},
			{
				// 推荐商品列表
				Method:  http.MethodGet,
				Path:    "/v1/recommend",
				Handler: RecommendHandler(serverCtx),
			},
		},
	)
}
