// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserID int `json:"userId"`
}

type UserInfoResp struct {
	UserID   int    `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateReq struct {
	UserID   int    `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateResp struct {
	Flag bool `json:"flag"`
}
