// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	ID int64 `path:"id"`
}

type UserInfoResp struct {
	ID       int64  `json:"id"`
	Nickname string `json:"nickname"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type UserUpdateReq struct {
	UserID   int    `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserUpdateResp struct {
	Flag bool `json:"flag"`
}

type UserListReq struct {
	Page     int    `form:"page"`
	PageSize int    `form:"pageSize"`
	Name     string `form:"name"`
}

type User struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Phone  string `json:"phone"`
	Email  string `json:"email"`
	Gender int64  `json:"gender"`
	Avatar string `json:"avatar"`
}

type UserListResp struct {
	List []User `json:"list"`
}
